name: "Home Budget"
description: "Home Budget"
version: "1.0.1"
slug: "home_budget"
init: false
ingress: true
ingress_port: 80
panel_icon: mdi:wallet
panel_title: Budget
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
options:
  target_url: "http://host:port" ## fix here
schema:
  target_url: str
