name: "Home Budget"
description: "Home Budget"
version: "1.0.1"
slug: "home_budget"
init: false
ingress: true
ingress_port: 80
panel_icon: mdi:wallet
panel_title: Budget
hassio_api: true
arch:
  - aarch64
  - amd64
startup: services
options:
  server_host: ""
  frontend_port: 3000
  backend_port: 8080
schema:
  server_host: str
  frontend_port: port
  backend_port: port
